
name: GitHub-Profile-3D-Contrib

on:
  schedule: #01:00 KST == 16:00 UTC
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: CastleSilver
      - name: Commit & Push
        run: |
          git config user.name bhs0906
          git config user.email hg5112@naver.com
          git add -A .
          git commit -m "generated"
          git push
